# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the minecraft version (without the 1.)
loaderVersion="[32,)" #mandatory

# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="" #optional

# A URL to refer people to when problems occur with this mod
#issueTrackerURL="" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="" #optional

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
license="Apache-2.0 License"

# A file name (in the root of the mod JAR) containing a logo for display
# logoFile="bettercolors.png" #optional

# A text field displayed in the mod UI
#credits="nero!, shorebre4k" #optional

# A text field displayed in the mod UI
authors="nero!" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="mcp" #mandatory

# The version number of the mod
version="7.4.0" #mandatory

# A display name for the mod
displayName="Bettercolors" #mandatory

# The description text for the mod (multi line!) (#mandatory)
description='''
Adjusts game's colors.
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.bettercolors]]
    modId="forge" #mandatory
    mandatory=false #mandatory
    versionRange="[32.0.0,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"