name: Build MC1.15.2

on:
  pull_request:
    branches: MC_1.15.2
  push:
    branches: MC_1.15.2

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build & test with Gradle
      run: chmod +x gradlew ; ./gradlew build ; ./gradlew test
